language: python
branches:
    only:
        - master
python:
    - "3.9"
    - "3.8"
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
    - pip install -U pytest-cov
    - pip install -U Cython
install:
    - pip3 install -r requirements.txt
script: pytest
after_success:
    - codecov
